// src/config/worlds.config.js
// 10 Savanna Worlds for QuadQuest (Grade 8 Quadrilaterals)

export const WORLDS = [
  {
    id: 0,
    name: "Meet the Species",
    emoji: "🦎",
    accent: "var(--world-0)",
    color: "#C9A227",
    description: "Identify the six special quadrilaterals by defining property",
    conceptFocus: "identify-special-quadrilaterals",
    boss: { name: "The Look-Alike Lurker", emoji: "🦎", reward: "Spotter Badge" },
  },
  {
    id: 1,
    name: "Four Corners",
    emoji: "🐊",
    accent: "var(--world-1)",
    color: "#7A9E3F",
    description: "Use the 360° angle sum to find a missing angle",
    conceptFocus: "angle-sum-quadrilateral",
    boss: { name: "The Four-Corner Croc", emoji: "🐊", reward: "Corner Badge" },
  },
  {
    id: 2,
    name: "Parallel Pairs",
    emoji: "🐍",
    accent: "var(--world-2)",
    color: "#B5651D",
    description: "Angle properties of parallelograms, trapeziums, kites",
    conceptFocus: "angle-properties-parallel",
    boss: { name: "The Parallel Python", emoji: "🐍", reward: "Parallel Badge" },
  },
  {
    id: 3,
    name: "Side by Side",
    emoji: "🐒",
    accent: "var(--world-3)",
    color: "#8E6C4A",
    description: "Side properties; unknown lengths and perimeters",
    conceptFocus: "side-properties-perimeter",
    boss: { name: "The Side-Swapping Baboon", emoji: "🐒", reward: "Sides Badge" },
  },
  {
    id: 4,
    name: "Cross Paths",
    emoji: "🐆",
    accent: "var(--world-4)",
    color: "#E0A458",
    description: "Diagonal properties of each special quadrilateral",
    conceptFocus: "diagonal-properties",
    boss: { name: "The Crossing Cheetah", emoji: "🐆", reward: "Diagonal Badge" },
  },
  {
    id: 5,
    name: "Name That Shape",
    emoji: "🦜",
    accent: "var(--world-5)",
    color: "#3F8F8F",
    description: "Classify from given properties; most specific name",
    conceptFocus: "classify-from-properties",
    boss: { name: "The Name-Game Parrot", emoji: "🦜", reward: "Namer Badge" },
  },
  {
    id: 6,
    name: "The Family Tree",
    emoji: "🐘",
    accent: "var(--world-6)",
    color: "#6B8E23",
    description: "All / some / no statements using the hierarchy",
    conceptFocus: "hierarchy-inclusion",
    boss: { name: "The Family-Tree Elephant", emoji: "🐘", reward: "Lineage Badge" },
  },
  {
    id: 7,
    name: "X Marks the Angle",
    emoji: "🐵",
    accent: "var(--world-7)",
    color: "#D95D39",
    description: "Form and solve equations from algebraic angle/side expressions",
    conceptFocus: "algebraic-angles-and-sides",
    boss: { name: "The Mystery-X Monkey", emoji: "🐵", reward: "Solver Badge" },
  },
  {
    id: 8,
    name: "Give Your Reasons",
    emoji: "🦏",
    accent: "var(--world-8)",
    color: "#5B4B8A",
    description: "Multi-step angle problems with a reason for each step",
    conceptFocus: "multi-step-with-reasons",
    boss: { name: "The Reasons Rhino", emoji: "🦏", reward: "Reasoner Badge" },
  },
  {
    id: 9,
    name: "The Grand Field Guide",
    emoji: "🏞️",
    accent: "var(--world-9)",
    color: "#2F3E2C",
    description: "Mixed review of every concept above; hardest boss",
    conceptFocus: "mixed-review",
    boss: { name: "The Chief Park Warden", emoji: "🏞️", reward: "Field Guide Champion Trophy" },
  },
];

export default WORLDS;
